# Use a smaller, minimal base image (Debian)
FROM debian:bullseye-slim

# Set non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary dependencies and Java 17
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    openjdk-17-jdk \
    wget \
    lib32z1 \
    lib32ncurses6 \
    lib32stdc++6 \
    qemu-kvm \
    libvirt-daemon-system \
    bridge-utils \
    xvfb \
    libgtk-3-0 \
    cmake \
    ninja-build \
    && apt-get clean

# Set JAVA_HOME to point to Java 17
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

# Set up Android SDK
ENV ANDROID_SDK_ROOT /opt/android-sdk-linux
RUN mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
ENV PATH ${PATH}:${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin:${ANDROID_SDK_ROOT}/platform-tools

# Download Android command line tools
RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O /tmp/cmdline-tools.zip && \
    unzip -q /tmp/cmdline-tools.zip -d ${ANDROID_SDK_ROOT}/cmdline-tools && \
    mv ${ANDROID_SDK_ROOT}/cmdline-tools/cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest && \
    rm /tmp/cmdline-tools.zip

# Accept licenses
RUN yes | sdkmanager --licenses

# Install Android SDK components
RUN sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "system-images;android-30;default;x86_64" "emulator"

# Download Flutter SDK
RUN git clone https://github.com/flutter/flutter.git -b stable /opt/flutter

# Add flutter to path
ENV PATH ${PATH}:/opt/flutter/bin

# Run basic check to download necessary SDK components
RUN flutter doctor

# Set the worki
